name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  file_selector: ^1.0.3
  charset_converter: ^2.0.0
  docx_viewer: ^1.0.1
  syncfusion_flutter_pdfviewer: ^31.2.2
  syncfusion_localizations: ^31.2.18
  open_filex: ^4.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  receive_sharing_intent: ^1.8.0
  shared_preferences: ^2.3.2

  archive: any
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon_fg.png"
  adaptive_icon_foreground: "assets/icons/icon_fg.png"
  adaptive_icon_background: "assets/icons/icon_bg.png"
  min_sdk_android: 21
